SET(DOTNET_OS "win")
SET(DOTNET_ARCH "x64")
SET(DOTNET_SDK_PATH "C:/Program Files/dotnet")
SET(DOTNET_VERSION "7.0.11")

SET(DOTNET_HOST_PACK_PATH "${DOTNET_SDK_PATH}/packs/Microsoft.NETCore.App.Host.${DOTNET_OS}-${DOTNET_ARCH}/${DOTNET_VERSION}")

SET(DOTNET_NATIVE_PATH "${DOTNET_HOST_PACK_PATH}/runtimes/${DOTNET_OS}-${DOTNET_ARCH}/native")

# set(TORQUE_LINK_LIBRARIES ${TORQUE_LINK_LIBRARIES} "${DOTNET_NATIVE_PATH}/nethost.lib")

set(TORQUE_LINK_LIBRARIES ${TORQUE_LINK_LIBRARIES} "${DOTNET_NATIVE_PATH}/nethost.lib")
set(TORQUE_INCLUDE_DIRECTORIES ${TORQUE_INCLUDE_DIRECTORIES} "${DOTNET_NATIVE_PATH}")

set(TORQUE_LINK_LIBRARIES ${TORQUE_LINK_LIBRARIES} PARENT_SCOPE)
set(TORQUE_INCLUDE_DIRECTORIES ${TORQUE_INCLUDE_DIRECTORIES} PARENT_SCOPE)

# This is a pain to use, but if we ever go about compiling nethost directly
# then it might come in handy
# set(TORQUE_COMPILE_DEFINITIONS ${TORQUE_COMPILE_DEFINITIONS} "NETHOST_USE_AS_STATIC" PARENT_SCOPE)

# Transfer dll
install(FILES "${DOTNET_NATIVE_PATH}/nethost.dll"
        DESTINATION "${TORQUE_APP_GAME_DIRECTORY}/nethost.dll")

message(WARNING "installed ${DOTNET_NATIVE_PATH}/nethost.dll into ${TORQUE_APP_GAME_DIRECTORY}")
